jdx/usage

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
* `usage-cli`: 0.1.9 -> 0.1.10
* `usage-lib`: 0.1.9 -> 0.1.10
<details><summary><i><b>Changelog</b></i></summary><p>
<blockquote>
- *(deps)* update rust crate heck to v0.5.0 ([#30](https://github.com/jdx/usage/pull/30))
- move usage-lib into its own dir
- added author field
</blockquote>
</p></details>
---
This PR was generated with [release-plz](https://github.com/MarcoIeni/release-plz/).
> chore: release

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
---
- update dependency vitepress to v1.0.1 (#42) by [@renovate[bot]](https://github.com/renovate[bot]) in [#42](https://github.com/jdx/usage/pull/42)
- update actions/configure-pages action to v5 (#44) by [@renovate[bot]](https://github.com/renovate[bot]) in [#44](https://github.com/jdx/usage/pull/44)
- lock file maintenance (#45) by [@renovate[bot]](https://github.com/renovate[bot]) in [#45](https://github.com/jdx/usage/pull/45)
- update dependency vitepress to v1.0.2 (#46) by [@renovate[bot]](https://github.com/renovate[bot]) in [#46](https://github.com/jdx/usage/pull/46)
- lock file maintenance (#47) by [@renovate[bot]](https://github.com/renovate[bot]) in [#47](https://github.com/jdx/usage/pull/47)
- **(changelog)** ran git-cliff by [@jdx](https://github.com/jdx) in …
> Release v0.1.18

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- **(exec)** added `usage exec` command by [@jdx](https://github.com/jdx) in [#51](https://github.com/jdx/usage/pull/51)
- rust beta warning by [@jdx](https://github.com/jdx) in [8ba775e](https://github.com/jdx/usage/commit/8ba775e02daef37193fa0f43d59f4a4ad3081056)
- created reusuable CLI parse function by [@jdx](https://github.com/jdx) in [8bc895a](https://github.com/jdx/usage/commit/8bc895a02ba6c7df32d47d0847b5b1985a2dbfdb)
- set GA by [@jdx](https://github.com/jdx) in [1a786c3](https://github.com/jdx/usage/commit/1a786c354a6e3f147453d8e6f38fb3916d21f889)
- update cliff.toml by [@jdx](https://github.com/jdx) in [df5f579](https://github.com/jdx/usage/commit/df5f579deac8d6f0fa2b0d2a492847950e338c94)
- **(aur)** added aur packaging by [@jdx](https://github.com/jdx) in …
> chore: release v0.2.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- updated deps by [@jdx](https://github.com/jdx) in [a457da9](https://github.com/jdx/usage/commit/a457da9ccec4890d63f3ab8e2215e51e64fd2425)
- update rust crate xx to v1 by [@renovate[bot]](https://github.com/renovate[bot]) in [#64](https://github.com/jdx/usage/pull/64)
- lock file maintenance by [@renovate[bot]](https://github.com/renovate[bot]) in [#65](https://github.com/jdx/usage/pull/65)
- update rust crate serde to v1.0.202 by [@renovate[bot]](https://github.com/renovate[bot]) in [#68](https://github.com/jdx/usage/pull/68)
- update rust crate thiserror to v1.0.61 by [@renovate[bot]](https://github.com/renovate[bot]) in [#69](https://github.com/jdx/usage/pull/69)
> chore: release v0.2.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- complete descriptions by [@jdx](https://github.com/jdx) in [a8afca7](https://github.com/jdx/usage/commit/a8afca7d6ad773431acfde8280e9dfb2884ef4e0)
> chore: release v0.3.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- **(brew)** use official homebrew formula by [@jdx](https://github.com/jdx) in [#54](https://github.com/jdx/usage/pull/54)
- make shebang scripts work with comments by [@jdx](https://github.com/jdx) in [9eb2a64](https://github.com/jdx/usage/commit/9eb2a64ff0e3c463f53fe0c283bbb932e5b3dd77)
- update dependency vitepress to v1.2.2 by [@renovate[bot]](https://github.com/renovate[bot]) in [#72](https://github.com/jdx/usage/pull/72)
- lock file maintenance by [@renovate[bot]](https://github.com/renovate[bot]) in [#73](https://github.com/jdx/usage/pull/73)
- update rust crate tera to v1.20.0 by [@renovate[bot]](https://github.com/renovate[bot]) in [#75](https://github.com/jdx/usage/pull/75)
- lock file maintenance by [@renovate[bot]](https://github.com/renovate[bot]) in …
> chore: release v0.3.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- add comment syntax for file scripts by [@jdx](https://github.com/jdx) in [ee75493](https://github.com/jdx/usage/commit/ee7549303a0cf63c5da8257287be21d0af85ce86)
- tweak comment syntax by [@jdx](https://github.com/jdx) in [dfff6e2](https://github.com/jdx/usage/commit/dfff6e2daaafb47200a32d4654482beabbe2f343)
- update flag syntax by [@jdx](https://github.com/jdx) in [a67de2e](https://github.com/jdx/usage/commit/a67de2e6e855b24d340d559ded9e1464f95c2894)
- update rust crate serde to v1.0.210 by [@renovate[bot]](https://github.com/renovate[bot]) in [#102](https://github.com/jdx/usage/pull/102)
- update rust crate clap to v4.5.18 by [@renovate[bot]](https://github.com/renovate[bot]) in [#101](https://github.com/jdx/usage/pull/101)
> chore: release v0.4.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- added .as_env() to CLI parser by [@jdx](https://github.com/jdx) in [b1f6617](https://github.com/jdx/usage/commit/b1f66179b70a4bcdc6792add24a7b62e1afdd81d)
- added Spec::parse_script fn by [@jdx](https://github.com/jdx) in [124a705](https://github.com/jdx/usage/commit/124a7050c6b1b5bb502049204556b74b6e8a4b71)
> chore: release v0.5.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- bail instead of panic on CLI parse error by [@jdx](https://github.com/jdx) in [b935cca](https://github.com/jdx/usage/commit/b935ccae9a442378c71182293cd24380fdadf744)
> chore: release v0.5.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- negate by Jeff Dickey in [5d1b817](https://github.com/jdx/usage/commit/5d1b817d143227a03651502b7671c9b2853c92eb)
- negate by Jeff Dickey in [16f754d](https://github.com/jdx/usage/commit/16f754d1925c561198291b304cbf80c9ab2a4dee)
- mount by Jeff Dickey in [99530f4](https://github.com/jdx/usage/commit/99530f4682140e2b64f2625d844b840925e3d6ae)
- remove debug statements by Jeff Dickey in [664b592](https://github.com/jdx/usage/commit/664b592f4d8f7b96f24d3bb2ca2803df36fda512)
- export SpecMount by Jeff Dickey in [b44c4f1](https://github.com/jdx/usage/commit/b44c4f15c77dee10e59c136b52f52a844f4ee655)
- migrate away from deprecated git-cliff syntax by Jeff Dickey in [3062df9](https://github.com/jdx/usage/commit/3062df94a9ad7af3a2e57ba5e5e35d299daa6718)
> chore: release v0.6.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- implemented choices for args/flags by jdx in [3db63bd](https://github.com/jdx/usage/commit/3db63bd540d3fe796136218bdf6862f27a678767)
- clean up pub exports by Jeff Dickey in [9996ab8](https://github.com/jdx/usage/commit/9996ab8ca041d27a0754096fe7b04ebd3958431b)
Fixes https://github.com/jdx/mise/issues/2670
> chore: release v0.7.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- fail parsing if required args/flags not found by [@jdx](https://github.com/jdx) in [409145a](https://github.com/jdx/usage/commit/409145ae5db937bffa121e63f00f8f827c49b294)
- publish aur releases by [@jdx](https://github.com/jdx) in [#109](https://github.com/jdx/usage/pull/109)
- move tasks dir by [@jdx](https://github.com/jdx) in [8cb8cc3](https://github.com/jdx/usage/commit/8cb8cc348dbb04f3c41f3ca22c518f82dfa27830)
- install cargo-binstall before installing mise by [@jdx](https://github.com/jdx) in [6240460](https://github.com/jdx/usage/commit/62404602e602a1c7d578b5764703f0820c45299e)
> chore: release v0.7.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- set GITHUB_TOKEN by [@jdx](https://github.com/jdx) in [fc7d06f](https://github.com/jdx/usage/commit/fc7d06ff15ca7b72d421fd3706c22b9e632b2224)
- fix codesign config by [@jdx](https://github.com/jdx) in [cf0b731](https://github.com/jdx/usage/commit/cf0b7311806d60b9d1e79c671958205156818311)
> chore: release v0.7.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- fix aur publishing by [@jdx](https://github.com/jdx) in [28752c3](https://github.com/jdx/usage/commit/28752c35f310bb78e45ab67c11b905e8af28b6c4)
> chore: release v0.7.4

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- basic support for markdown generation in lib by [@jdx](https://github.com/jdx) in [de004c8](https://github.com/jdx/usage/commit/de004c87890bda993288503fe49e02b342c72487)
- enable aur publishing by [@jdx](https://github.com/jdx) in [0049e95](https://github.com/jdx/usage/commit/0049e950001bf8a9dfb350d5e675c474f6958d18)
> chore: release v0.8.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- handle bug with usage-bin aur script by [@jdx](https://github.com/jdx) in [6e4b7a7](https://github.com/jdx/usage/commit/6e4b7a79be85d5b02285718625f6302bef75cb75)
- improving md generation by [@jdx](https://github.com/jdx) in [#117](https://github.com/jdx/usage/pull/117)
- enable brew publish by [@jdx](https://github.com/jdx) in [d8cd84a](https://github.com/jdx/usage/commit/d8cd84afbf4ae21386fda4b5a01d0adeaf7839a9)
> chore: release v0.8.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- whitespace in md generation by [@jdx](https://github.com/jdx) in [3cb7769](https://github.com/jdx/usage/commit/3cb776920cd9bd18693cdc0e547b98b0efd25aca)
- escape html in md by [@jdx](https://github.com/jdx) in [a691143](https://github.com/jdx/usage/commit/a6911436156c15246c69ea66e62e2745e419b813)
- more work on html encoding md by [@jdx](https://github.com/jdx) in [b5cb342](https://github.com/jdx/usage/commit/b5cb342fa79ac70bd2723c026f3184021e5ae3ac)
> chore: release v0.8.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- minor whitespace bug in md output by [@jdx](https://github.com/jdx) in [dcced73](https://github.com/jdx/usage/commit/dcced7300a3abfd2cde2eee2879d27fa30b50694)
- added aliases to command info by [@jdx](https://github.com/jdx) in [ac745d6](https://github.com/jdx/usage/commit/ac745d66215566500faa684b93192392bf307521)
- tweak usage output by [@jdx](https://github.com/jdx) in [c488b76](https://github.com/jdx/usage/commit/c488b76249c6ab6eb022cc022567faed82332074)
- make html_encode optional by [@jdx](https://github.com/jdx) in [cc629ee](https://github.com/jdx/usage/commit/cc629ee36acbbd2fe9a4e69c4b3216334f356739)
- always remove aur repo by [@jdx](https://github.com/jdx) in [368ae97](https://github.com/jdx/usage/commit/368ae97a73ecb82fb5855fdc8610dc7e2dd17084)
> chore: release v0.8.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- capitalize ARGS/FLAGS in md docs by [@jdx](https://github.com/jdx) in [3a314d5](https://github.com/jdx/usage/commit/3a314d5bcb7a1552a4cf2e833bd81b35a7e9e514)
- move usage out of header by [@jdx](https://github.com/jdx) in [9a43a72](https://github.com/jdx/usage/commit/9a43a72ae26606cc9c03ee718627c1a6636d77f2)
- fix aur by [@jdx](https://github.com/jdx) in [56a0cf7](https://github.com/jdx/usage/commit/56a0cf7250890dd7147e41d69f3942150fdbd5d5)
> chore: release v0.8.4

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- put aliases in backticks by [@jdx](https://github.com/jdx) in [36b527f](https://github.com/jdx/usage/commit/36b527f8aaa9c64aadfb7dce06243625b28e091e)
- make `usage -v` work by [@jdx](https://github.com/jdx) in [caabb0f](https://github.com/jdx/usage/commit/caabb0f92f744bd1bcd0e1321c27649861b8ccea)
- remove quotes in zsh descriptions by [@jdx](https://github.com/jdx) in [dba5fd8](https://github.com/jdx/usage/commit/dba5fd8ec4f08938ff6fc127f3542ef48deb8ca2)
- use correct url for aur checksum by [@jdx](https://github.com/jdx) in [36d577e](https://github.com/jdx/usage/commit/36d577eca41c290d47d03ad74783870eca806788)
- update rust crate once_cell to v1.20.1 by [@renovate[bot]](https://github.com/renovate[bot]) in [#123](https://github.com/jdx/usage/pull/123)
- update rust crate regex to …
> chore: release v0.9.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- basic `--help` support by [@jdx](https://github.com/jdx) in [394df50](https://github.com/jdx/usage/commit/394df50623de7d497de47975267a4b7ec9377e70)
- debug output by [@jdx](https://github.com/jdx) in [53a4fe4](https://github.com/jdx/usage/commit/53a4fe4c155115e15dfe066844d83aa66c9bab83)
> chore: release v0.10.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- support single quotes in zsh descriptions by [@jasisk](https://github.com/jasisk) in [#128](https://github.com/jdx/usage/pull/128)
- render help in cli parsing by [@jdx](https://github.com/jdx) in [7c49fcb](https://github.com/jdx/usage/commit/7c49fcba4567da7ad8c7af9c4bb72a7c276a4a57)
- implemented more cli help for args/flags/subcommands by [@jdx](https://github.com/jdx) in [669f44e](https://github.com/jdx/usage/commit/669f44ea0459f997444c46ebfac1f42c00e210b4)
- bug with help and args by [@jdx](https://github.com/jdx) in [6c615f9](https://github.com/jdx/usage/commit/6c615f9f8b1c6798fcba3ed88890b2891505c6ec)
- use dashes in CHANGELOG by [@jdx](https://github.com/jdx) in [c458d8c](https://github.com/jdx/usage/commit/c458d8c8a4c810271ac2474fcb9412651edc8c86)
- remove dbg by …
> chore: release v0.11.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- fixed default arg/flags by [@jdx](https://github.com/jdx) in [#135](https://github.com/jdx/usage/pull/135)
- read choices from clap args by [@jdx](https://github.com/jdx) in [#136](https://github.com/jdx/usage/pull/136)
- update dawidd6/action-homebrew-bump-formula action to v4 by [@renovate[bot]](https://github.com/renovate[bot]) in [#131](https://github.com/jdx/usage/pull/131)
- update dependency vitepress to v1.4.1 by [@renovate[bot]](https://github.com/renovate[bot]) in [#130](https://github.com/jdx/usage/pull/130)
> chore: release v0.11.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- added source code links by [@jdx](https://github.com/jdx) in [6bc9c84](https://github.com/jdx/usage/commit/6bc9c84fc7a6efaf09e30af75925488f761834bd)
- use prettier-compatible md list syntax by [@jdx](https://github.com/jdx) in [2726bf2](https://github.com/jdx/usage/commit/2726bf22e7c4fabb48322b58813ff50bda698fe5)
> chore: release v0.12.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- added backticks around source code link by [@jdx](https://github.com/jdx) in [53121fa](https://github.com/jdx/usage/commit/53121fabc8bcb3603474b0864a6f9add592bcabf)
- bug with missing source code template by [@jdx](https://github.com/jdx) in [3e3e303](https://github.com/jdx/usage/commit/3e3e30389a9c508b30f00c3751152ea51d2fc8fa)
> chore: release v0.12.1

- cli/src/cli/generate/completion.rs
- lib/src/complete/bash.rs
- lib/src/complete/fish.rs
- lib/src/complete/zsh.rs
- mise.lock
- mise.toml
> fix: allow calling `usage g completion -f`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- lib/Cargo.toml
- allow calling `usage g completion -f` by [@jdx](https://github.com/jdx) in [#143](https://github.com/jdx/usage/pull/143)
- add bin name to `mise g completion` examples by [@jdx](https://github.com/jdx) in [8892b5b](https://github.com/jdx/usage/commit/8892b5b8c706ad4db46aa70753718436ec464fee)
> chore: release v1.0.1

- .codacy.yml
- .prettierignore
- Cargo.lock
- cli/Cargo.toml
- cli/src/cli/generate/fig.rs
- cli/src/cli/generate/mod.rs
- cli/usage.usage.kdl
- docs/cli/reference.md
- tasks/fig/generators.ts
Add a subcommand to `generate` to create a Fig Spec which can be integrated with Amazon CloudWhisperer CLI/Amazon Q/Fig.
Example usage:
`usage g fig -f mise.usage.kdl --out-file tasks/fig/src/mise.ts`
Can be compiled into javascript using the following command on `tasks/fig` folder: `npx @withfig/autocomplete-tools compile` and used locally by moving the resulting `build/mise.js` into `~/.fig/autocomplete/build` (if the folders don't exist just create them)
> Add fig generate completion subcommand

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference.md
- lib/Cargo.toml
- added clap_usage by [@jdx](https://github.com/jdx) in [#150](https://github.com/jdx/usage/pull/150)
- added completions for usage-cli itself by [@jdx](https://github.com/jdx) in [#151](https://github.com/jdx/usage/pull/151)
- pass exit codes with `usage bash` and `usage exec` by [@jdx](https://github.com/jdx) in [#152](https://github.com/jdx/usage/pull/152)
- tweaks to fig completions by [@jdx](https://github.com/jdx) in [#153](https://github.com/jdx/usage/pull/153)
- Include the generator for mount run commands by [@miguelmig](https://github.com/miguelmig) in [#154](https://github.com/jdx/usage/pull/154)
- fix highlighting by [@jdx](https://github.com/jdx) in [c03b934](https://github.com/jdx/usage/commit/c03b9348d0472891eef45a4ca4db1786bdb3683e)
- generate markdown examples by …
> chore: release v1.1.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference.md
- lib/Cargo.toml
- added cache-key to generated completions by [@jdx](https://github.com/jdx) in [#159](https://github.com/jdx/usage/pull/159)
- require --file or --usage-cmd on `usage g completion` by [@jdx](https://github.com/jdx) in [3cae2ae](https://github.com/jdx/usage/commit/3cae2ae4a1ad6a97358bb49d9d0f3e15c65feb40)
> chore: release v1.2.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference.md
- lib/Cargo.toml
- min_usage_version by [@jdx](https://github.com/jdx) in [#166](https://github.com/jdx/usage/pull/166)
- **(fig)** better generate spec for fig mount commands by [@miguelmig](https://github.com/miguelmig) in [#165](https://github.com/jdx/usage/pull/165)
- completions for bins with dashes by [@jdx](https://github.com/jdx) in [adbb347](https://github.com/jdx/usage/commit/adbb3478b86a4eede4f9812c73fc547f13f00842)
- bash script with snake case escapes by [@jdx](https://github.com/jdx) in [4e5ba4a](https://github.com/jdx/usage/commit/4e5ba4a6fa9d3adfe04c27a24b489c15af94ef69)
- update dependency vitepress to v1.5.0 by [@renovate[bot]](https://github.com/renovate[bot]) in [#160](https://github.com/jdx/usage/pull/160)
> chore: release v1.3.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference.md
- lib/Cargo.toml
- space-separate multi-args by [@jdx](https://github.com/jdx) in [4054034](https://github.com/jdx/usage/commit/4054034bb12414fd179c17a105855e86544d497a)
> chore: release v1.3.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference.md
- lib/Cargo.toml
- unset arg/flag required if default provided by [@jdx](https://github.com/jdx) in [#175](https://github.com/jdx/usage/pull/175)
- added shellcheck disable comment for bash completion by [@jdx](https://github.com/jdx) in [7e1da8f](https://github.com/jdx/usage/commit/7e1da8fabc78d94f752c59b09bb83e4b18ec0bfe)
> chore: release v1.3.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference.md
- lib/Cargo.toml
- added shellcheck for bash completion file by [@jdx](https://github.com/jdx) in [#176](https://github.com/jdx/usage/pull/176)
- skip autofix on renovate prs by [@jdx](https://github.com/jdx) in [ada6c92](https://github.com/jdx/usage/commit/ada6c92da40d54d3afcba9a6366213a22f215272)
- pin kdl below 4.7 by [@jdx](https://github.com/jdx) in [045c9cf](https://github.com/jdx/usage/commit/045c9cf7edc6b9764fd9a794afbbde5b21ddba76)
> chore: release v1.3.4

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference.md
- lib/Cargo.toml
- Update README.md by [@jdx](https://github.com/jdx) in [3fc2181](https://github.com/jdx/usage/commit/3fc218107b0f911169a58f2c8dba3fba7e6bcdc3)
- bump to miette-7 by [@jdx](https://github.com/jdx) in [#21](https://github.com/jdx/usage/pull/21)
> chore: release v1.3.5

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- `usage g json` by [@jdx](https://github.com/jdx) in [#184](https://github.com/jdx/usage/pull/184)
- bug with completing default args/flags by [@jdx](https://github.com/jdx) in [#185](https://github.com/jdx/usage/pull/185)
- added completes to string output by [@jdx](https://github.com/jdx) in [#186](https://github.com/jdx/usage/pull/186)
- added completes to string output by [@jdx](https://github.com/jdx) in [#187](https://github.com/jdx/usage/pull/187)
- added completes to cmds by [@jdx](https://github.com/jdx) in [f421d9e](https://github.com/jdx/usage/commit/f421d9e5b8a88eae70914ff0be44bee824dc0aa1)
- fix links by [@jdx](https://github.com/jdx) in [46be80a](https://github.com/jdx/usage/commit/46be80a48d2174167546ecbf3b3e3cf32487d4b8)
- fix links by [@jdx](https://github.com/jdx) in …
> chore: release v1.4.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- handle colons in bash completions by [@jdx](https://github.com/jdx) in [240ea41](https://github.com/jdx/usage/commit/240ea418e6bcadfacca70a14670cd10de1086cbe)
- handle colons in zsh completions by [@jdx](https://github.com/jdx) in [455b6f7](https://github.com/jdx/usage/commit/455b6f7435d07c6a9a2c20d82584da96c5ae5933)
- snapshots by [@jdx](https://github.com/jdx) in [4ab650f](https://github.com/jdx/usage/commit/4ab650f1e4b6bf35491f538f99d42a121702f173)
- add bash-completions to lib by [@jdx](https://github.com/jdx) in [8450ff7](https://github.com/jdx/usage/commit/8450ff7c15149d926a948c6f291b2d727bb607ce)
- submodules by [@jdx](https://github.com/jdx) in [83d68a9](https://github.com/jdx/usage/commit/83d68a9976e778e3e98744f850b07be82a42e49a)
- submodules by [@jdx](https://github.com/jdx) …
> chore: release v1.4.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- descriptions in completions by [@jdx](https://github.com/jdx) in [ef73a40](https://github.com/jdx/usage/commit/ef73a40be990a611df13bb9f662fb5d1e1538651)
> chore: release v1.5.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- remove submodule by [@jdx](https://github.com/jdx) in [5922490](https://github.com/jdx/usage/commit/5922490244dd43f7e7852aa5be8eef3c549671de)
> chore: release v1.5.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- remove debug @usage by [@jdx](https://github.com/jdx) in [8178c97](https://github.com/jdx/usage/commit/8178c97f3004bcacb4827083c5cb46fa23bff64e)
> chore: release v1.5.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- bash completion escape by [@jdx](https://github.com/jdx) in [ce80f20](https://github.com/jdx/usage/commit/ce80f207b609f251515ba0889844cd694ed6f820)
- snapshots by [@jdx](https://github.com/jdx) in [d15bd90](https://github.com/jdx/usage/commit/d15bd90af4d67440219182c287959013ca56b8d3)
- add snapshots to pre-commit by [@jdx](https://github.com/jdx) in [9d19066](https://github.com/jdx/usage/commit/9d1906603bd0ea505928a4423b78bb4edd744b18)
> chore: release v1.5.3

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- feature for automatically adding code fences by [@jdx](https://github.com/jdx) in [#197](https://github.com/jdx/usage/pull/197)
- make bash_completion optional by [@jdx](https://github.com/jdx) in [6705de4](https://github.com/jdx/usage/commit/6705de473fbd2207be2f933c051a48188029b069)
> chore: release v1.6.0

- cli/Cargo.toml
- cli/src/cli/generate/completion.rs
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/generate/completion.md
- lib/src/complete/bash.rs
- lib/src/complete/fish.rs
- lib/src/complete/mod.rs
- lib/src/complete/zsh.rs
- mise.toml
Fixes https://github.com/jdx/mise/issues/2008
> fix: allow overriding usage in case of conflict

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- added double_dash option to args by [@jdx](https://github.com/jdx) in [#202](https://github.com/jdx/usage/pull/202)
- allow overriding `usage` in case of conflict by [@jdx](https://github.com/jdx) in [#198](https://github.com/jdx/usage/pull/198)
- join code fences if they are right next to each other by [@jdx](https://github.com/jdx) in [#200](https://github.com/jdx/usage/pull/200)
- default cmd help types by [@jdx](https://github.com/jdx) in [#203](https://github.com/jdx/usage/pull/203)
- disable cargo up in release-plz by [@jdx](https://github.com/jdx) in [16a36b7](https://github.com/jdx/usage/commit/16a36b78673b40a98a4701e30d5222f4a1b4bb95)
> chore: release v1.7.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- clean up double_dash rendering by [@jdx](https://github.com/jdx) in [eac7db8](https://github.com/jdx/usage/commit/eac7db8a68ded04f6c2260fe68a5bba2867a3a5d)
> chore: release v1.7.2

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- expose spec.merge method by [@jdx](https://github.com/jdx) in [6de998c](https://github.com/jdx/usage/commit/6de998c00ec15b5bca70bbd46cb5700d9e620861)
> chore: release v1.7.4

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- **breaking** kdl 2.0 by [@jdx](https://github.com/jdx) in [#218](https://github.com/jdx/usage/pull/218)
- **(fish)** remove deprecated completion option by [@jdx](https://github.com/jdx) in [#217](https://github.com/jdx/usage/pull/217)
- make compatible with ancient bash by [@jdx](https://github.com/jdx) in [9e76a17](https://github.com/jdx/usage/commit/9e76a17e433fde50d15c3250aef693f378c17efc)
- add source_code_link_template example by [@jdx](https://github.com/jdx) in [cb1f7b4](https://github.com/jdx/usage/commit/cb1f7b4b0bacd66b0928b291d3e58fc3c93d18a3)
- Update LICENSE by [@jdx](https://github.com/jdx) in [e27b7d9](https://github.com/jdx/usage/commit/e27b7d9cbbbe096a844dde9ace93bfebd35e2e63)
- remove unused custom homebrew tap by [@jdx](https://github.com/jdx) in …
> chore: release v2.0.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- add v1-fallback for kdl by [@jdx](https://github.com/jdx) in [9516e15](https://github.com/jdx/usage/commit/9516e15d53c0769a1227ec4ab37e0622b4e7bead)
- fix publish script by [@jdx](https://github.com/jdx) in [7c72bc3](https://github.com/jdx/usage/commit/7c72bc3450fe0e731331be18354244b5a19223d5)
- configure render:fig task by [@jdx](https://github.com/jdx) in [f744199](https://github.com/jdx/usage/commit/f744199b53de9272cf62ab6c760c9da1239fa626)
- fix fig syntax rendering by [@jdx](https://github.com/jdx) in [2b2d301](https://github.com/jdx/usage/commit/2b2d30104280c64854b78d829547a5d3fa8694df)
> chore: release v2.0.1

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- package.json
- pnpm-lock.yaml
- bump clap_usage by [@jdx](https://github.com/jdx) in [d896d24](https://github.com/jdx/usage/commit/d896d24911892969b36e51e03465d442fa040652)
- use ubuntu-20.04 for publishing by [@jdx](https://github.com/jdx) in [d1d6989](https://github.com/jdx/usage/commit/d1d6989814ebbc24aafd59621ea3cb5d63fe8a2e)
- bump npm packages on releases by [@jdx](https://github.com/jdx) in [c24e25d](https://github.com/jdx/usage/commit/c24e25d92fd43e6e79703cdffcf2394d941cd109)
- added pnpm by [@jdx](https://github.com/jdx) in [4c517fb](https://github.com/jdx/usage/commit/4c517fbdff91849e2a9525432833f5e58d0d7385)
> chore: release v2.0.4

- lib/src/parse.rs
- lib/tests/parse.rs
mise was not handling flags with values and var=#true with short flags
it also was not using shell_words::join to provide var flag values in env vars
Fixes https://github.com/jdx/mise/discussions/4294
Fixes https://github.com/jdx/mise/issues/4295
> fix: 2 bugs with flags and var=#true

- lib/src/parse.rs
Required to simply implement https://github.com/jdx/mise/pull/4605.
> fix(lib): make `ParseValue` cloneable

- cli/src/cli/complete_word.rs
- docs/cli/scripts.md
- lib/src/parse.rs
- lib/tests/parse.rs
This change introduces a fix to support short flag chaining in the core parsing LIB for the CLI. Previously, chaining flags (e.g., -abc) resulted in an error where the tool misinterpreted the flags as a single argument (bc). With this update, the CLI now properly parses chained flags and applies them individually.
**Changes Made:**
- Modified flag-parsing logic to recognize chained short flags.
- Added unit tests to ensure correct functionality of short flag chaining.
- Updated documentation to reflect support for flag chaining.
To implement this change, I modified the logic to adjust the order in which flags are processed. Now, only the last valid short flag in a chain can accept the next argument value. For instance, in the command `./mycli -abc 123`, the value `123` would be assigned …
> fix: (#257) implement short flag chaining and update flag handling logic

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- pnpm-lock.yaml
- implement short flag chaining and update flag handling logic by [@aroemen](https://github.com/aroemen) in [#258](https://github.com/jdx/usage/pull/258)
- Fix some typos in completions.md by [@torarvid](https://github.com/torarvid) in [#253](https://github.com/jdx/usage/pull/253)
- updated deps by [@jdx](https://github.com/jdx) in [7a498e6](https://github.com/jdx/usage/commit/7a498e60e90420af8bec0e97ddbc9f69fdbcd8d5)
- update apple-actions/import-codesign-certs action to v4 by [@renovate[bot]](https://github.com/renovate[bot]) in [#256](https://github.com/jdx/usage/pull/256)
- update dependency vitepress to v1.6.3 by [@renovate[bot]](https://github.com/renovate[bot]) in [#255](https://github.com/jdx/usage/pull/255)
- @aroemen made their first contribution in …
> chore: release v2.0.7

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- package.json
- pnpm-lock.yaml
- use ellipsis character by [@jdx](https://github.com/jdx) in [#269](https://github.com/jdx/usage/pull/269)
- upgrade ubuntu by [@jdx](https://github.com/jdx) in [3f71633](https://github.com/jdx/usage/commit/3f71633bd7be4c337e3584bed20d35c7355cb5e7)
- update apple-actions/import-codesign-certs action to v5 by [@renovate[bot]](https://github.com/renovate[bot]) in [#262](https://github.com/jdx/usage/pull/262)
> chore: release v2.1.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- dry run releases by [@jdx](https://github.com/jdx) in [67cd3d6](https://github.com/jdx/usage/commit/67cd3d615b60ea7c3a0f0e2d63e0932b99c7b62a)
- fix releases by [@jdx](https://github.com/jdx) in [#272](https://github.com/jdx/usage/pull/272)
> chore: release v2.1.1

- cli/assets/fig.ts
- cli/src/cli/mod.rs
- cli/src/cli/shell.rs
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/fish.md
- docs/cli/reference/index.md
- docs/cli/reference/zsh.md
- mise.toml
this pr adds `usage zsh` and `usage fish`, the behavior is the same as `usage bash` except with the respective shells.
This is done by renaming `Bash` -> `Shell` and adding an arg to the run method that lets you specify which shell is being used.
alternatives considered:
- `usage shell --shell=<shell>` this is the most flexible but also is a bigger footgun, it also looks cumbersome in the shebang of a script.
> Generalize bash command to support bash/zsh/fish

- docs/cli/index.md
Hello @jdx , I see wrong name package manager on Arch. Can I fix this?
> fix: update wrong name package manager

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- package.json
- pnpm-lock.yaml
- Generalize bash command to support bash/zsh/fish by Adam Hitchcock in [c29f83b](https://github.com/jdx/usage/commit/c29f83b4556a9d75c9ed1c0f5fe31d5f5204200e)
- update wrong name package manager by Roman Sotnikov in [d1f8c04](https://github.com/jdx/usage/commit/d1f8c04ec07137f86fa810c0dfb8601c23569796)
- fall back to listing files on unknown completions by jdx in [f301789](https://github.com/jdx/usage/commit/f3017891e2ac3932362b111838e7ab17fdec3944)
- complete templates by Simon Holloway in [a8e429c](https://github.com/jdx/usage/commit/a8e429c139813bb0c741f937be905f61fdd773d9)
- fix bad whitespace character by Simon Holloway in [d95a5a1](https://github.com/jdx/usage/commit/d95a5a18bbc95cca1879903845bedb7528a67983)
- add semantic-pr-lint by jdx in …
> chore: release v2.2.0

- cli/assets/completions/_usage
- cli/assets/completions/usage.bash
- cli/assets/completions/usage.fish
- lib/src/complete/bash.rs
- lib/src/complete/fish.rs
- lib/src/complete/snapshots/usage__complete__bash__tests__complete_bash-2.snap
- lib/src/complete/snapshots/usage__complete__bash__tests__complete_bash-3.snap
- lib/src/complete/snapshots/usage__complete__bash__tests__complete_bash.snap
- lib/src/complete/snapshots/usage__complete__fish__tests__complete_fish-2.snap
- lib/src/complete/snapshots/usage__complete__fish__tests__complete_fish-3.snap
- lib/src/complete/snapshots/usage__complete__fish__tests__complete_fish.snap
- lib/src/complete/snapshots/usage__complete__zsh__tests__complete_zsh-2.snap
- lib/src/complete/snapshots/usage__complete__zsh__tests__complete_zsh-3.snap
- lib/src/complete/snapshots/usage__complete__zsh__tests__complete_zsh.snap
- lib/src/complete/zsh.rs
- mise.lock
Resolves https://github.com/jdx/mise/discussions/5358.
This PR replaces `usage` with `command usage`, to ignore aliases and functions named `usage`.
Also, for consistency, use `command usage` instead of `command -v usage` to check its existence.
In this way, if aliases or functions named `usage` exist but `usage` is not installed, the completions are skipped as expected.
I don't think this is a case, but something like `alias usage=usage --default-flag` will be ignored by this PR.
> fix(completions): ignore aliases and functions named usage

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- cli/Cargo.toml
- cli/usage.usage.kdl
- docs/cli/reference/commands.json
- docs/cli/reference/index.md
- lib/Cargo.toml
- fix revert for git-cliff by [@jdx](https://github.com/jdx) in [#302](https://github.com/jdx/usage/pull/302)
- Revert "fix(completions): ignore aliases and functions named usage" by [@jdx](https://github.com/jdx) in [#301](https://github.com/jdx/usage/pull/301)
> chore: release v2.2.2
